#!/bin/bash

# contains(string, substring)
#
# Returns 0 if the specified string contains the specified substring,
# otherwise returns 1.
command_exists() {
    scring="$1"
    if [ "${string#*"$substring"}" != "$string" ]; then
        return 0    # $substring is in $string
    else
        return 1    # $substring is not in $string
    fi
}

# base devel
if ! pacman -Q base-devel > /dev/null; then
  sudo pacman --noconfirm -S base-devel
fi

# git
if ! command -v git > /dev/null; then
  sudo pacman --noconfirm -S git
fi

# yay
if ! command -v yay > /dev/null; then
  cd $HOME
  mkdir -p src && cd src
  git clone https://aur.archlinux.org/yay-bin.git
  cd yay-bin
  makepkg -si
  cd $HOME
fi


# wezterm
if ! command -v git > /dev/null; then
  sudo pacman --noconfirm -S git
fi
